<?php

declare(strict_types=1);

namespace CertPath\Readiness;

use CertPath\Coverage\CoverageReport;
use CertPath\Domain\LotRegistry;

/**
 * The persistent readiness dashboard, regenerated from canonical data.
 *
 * There is no "generated at" timestamp. CI regenerates this file and fails on
 * any diff, so a clock in the output would fail the build on the next day for
 * no reason. The date shown is the last refinement RECORDED, which is canonical
 * and changes only when the work does.
 */
final readonly class ReadinessMarkdownRenderer
{
    /**
     * @param array<string, array{lot: string, date?: string, framework_version?: int}> $log
     *        entries from refinement-log.yml
     */
    public function render(
        ReadinessReport $readiness,
        CoverageReport $coverage,
        LotRegistry $lots,
        array $log = [],
        bool $forSite = false,
    ): string {
        $loggedFramework = [];
        foreach ($log as $entry) {
            if (\is_array($entry) && isset($entry['lot'])) {
                $loggedFramework[(string) $entry['lot']] = (int) (
                    $entry['framework_version'] ?? RefinementFramework::DEFAULT_FOR_UNVERSIONED_ENTRY
                );
            }
        }

        $rows = [];
        $ordered = $readiness->byLot;
        uksort($ordered, static fn (string $a, string $b): int => $lots->order($a) <=> $lots->order($b));

        foreach ($ordered as $lotId => $row) {
            $rows[] = \sprintf(
                '| %s | %s | %d | %d | %.0f%% |',
                $lots->label($lotId),
                $this->refinementCell($lotId, $row['audited'], $loggedFramework),
                $row['total'],
                $row['ready'],
                0 === $row['total'] ? 0.0 : $row['ready'] / $row['total'] * 100,
            );
        }

        $dist = $readiness->distribution();
        $lastDate = '';
        $lastLot = '';
        foreach ($log as $entry) {
            if (isset($entry['date']) && $entry['date'] >= $lastDate) {
                $lastDate = (string) $entry['date'];
                $lastLot = (string) ($entry['lot'] ?? '');
            }
        }

        $next = $this->nextLot($ordered, $lots);
        $currentFramework = RefinementFramework::CURRENT;

        return <<<MD
            # Symfony 8 Certification Path — readiness

            **Regenerated by `php bin/cert readiness`. Never edited by hand.**

            ## The two numbers are not the same number

            | | |
            |---|---|
            | **Official Coverage** | **{$this->pct($coverage->percentage())}** — {$coverage->examReadyItems} of {$coverage->totalOfficialItems} atomic official items are `EXAM_READY` |
            | **Certification Readiness** | **{$this->pct($readiness->percentage())}** — {$readiness->readyItems()} of {$readiness->totalItems()} are refined to the point where an unseen question is answerable |

            Coverage says the syllabus is covered. Readiness says how much of it
            has been refined so a candidate could answer a question they have
            never seen. **100% coverage is not 100% readiness**, and the day these
            two figures agree will be the day the work is finished — not before.

            ## Items

            | Status | Items | Meaning |
            |---|---|---|
            | `NOT_REFINED` | {$dist['NOT_REFINED']} | fails a criterion its content level requires |
            | `PARTIALLY_REFINED` | {$dist['PARTIALLY_REFINED']} | meets every automated criterion; its lot has had no refinement audit |
            | `REFINED` | {$dist['REFINED']} | meets every criterion, in a lot whose refinement audit is recorded |
            | `MASTERED_READY` | {$dist['MASTERED_READY']} | refined, and assessable in exam mode at the top of what its level requires |

            Only `REFINED` and `MASTERED_READY` count toward Certification
            Readiness. {$this->formulaPointer($forSite)}

            ## Lots

            **{$readiness->lotsRefined()} of {$readiness->declaredLots} lots refined.**

            | Lot | Refinement | Items | Ready | Lot readiness |
            |---|---|---|---|---|
            {$this->join($rows)}

            A lot audited under an earlier definition of refinement keeps its
            record and is shown with the version it was audited against. It is
            not counted as refined here, because it does not carry what the
            current definition requires; the audit is real, the bar moved. The
            current definition is framework version {$currentFramework} — see
            `docs/adr/0007-refinement-framework-v2.md`.

            Lot 27 carries no atomic official item — it consolidates the final
            review, the mocks and the holdout — so it has no row above while
            still counting in the denominator.

            ## Where the work stands

            | | |
            |---|---|
            | Last completed | {$this->lotLabel($lastLot, $lots)} |
            | Recorded on | {$this->orNone($lastDate)} |
            | Next | {$this->lotLabel($next, $lots)} |

            MD;
    }

    /**
     * @param array<string, int> $loggedFramework lot id => framework version audited against
     */
    private function refinementCell(string $lotId, bool $audited, array $loggedFramework): string
    {
        if ($audited) {
            return '**REFINED**';
        }

        $version = $loggedFramework[$lotId] ?? null;

        return null === $version ? 'TODO' : \sprintf('audited under framework v%d', $version);
    }

    /**
     * The repository copy links to the formula; the generated site page names
     * it instead, because `docs/policy/` is not published and LNK-001 rejects a
     * link that resolves to nothing.
     */
    private function formulaPointer(bool $forSite): string
    {
        return $forSite
            ? 'The formula, and why the automated criteria alone are not enough, '
              .'are recorded in `docs/policy/readiness-formula.md` in the repository.'
            : 'The formula, and why the automated criteria alone are not enough, '
              .'are in [`docs/policy/readiness-formula.md`](../policy/readiness-formula.md).';
    }

    /** @param array<string, array{audited: bool}> $ordered */
    private function nextLot(array $ordered, LotRegistry $lots): string
    {
        foreach ($ordered as $lotId => $row) {
            if (!$row['audited']) {
                return $lotId;
            }
        }

        return '';
    }

    private function lotLabel(string $lotId, LotRegistry $lots): string
    {
        return '' === $lotId ? '_none_' : $lots->label($lotId);
    }

    private function orNone(string $value): string
    {
        return '' === $value ? '_none_' : $value;
    }

    private function pct(float $value): string
    {
        return rtrim(rtrim(number_format($value, 1, '.', ''), '0'), '.').'%';
    }

    /** @param list<string> $rows */
    private function join(array $rows): string
    {
        return implode("\n", $rows);
    }
}
