/**
 * The agenda model behind the revision calendar.
 *
 * Everything here is a projection of `docs/revision/plan.json`, generated by
 * `tools/revision/build_roadmap.py` and copied into `static/data/` by
 * `DocsGenerator`. No duration is computed in the browser: a figure the page
 * invented would disagree with the Markdown calendar the moment either
 * changed, and there would be no way to tell which one was right.
 */

export type EventKind =
  | 'NEW'
  | 'REVIEW'
  | 'LAB'
  | 'ASSESS'
  | 'MOCK'
  | 'CONSOLIDATION'
  | 'EXAM';

export interface PlanEvent {
  start: string;
  end: string;
  minutes: number;
  kind: EventKind;
  title: string;
  lot: string | null;
  objective: string;
}

export interface PlanDay {
  events: PlanEvent[];
  milestone: [string, string] | null;
  used: number;
  budget: number;
}

export interface CalendarPayload {
  generated_from: string;
  start: string | null;
  exam: string | null;
  all_items_in: string | null;
  last_day: string | null;
  day_start: Record<string, string>;
  mock_dates: [string, string][];
  lot_name: Record<string, string>;
  lost_reviews_by_offset: Record<string, number>;
  lost_reviews_minutes: number;
  days: Record<string, PlanDay>;
}

export const KIND_LABEL: Record<EventKind, string> = {
  NEW: 'Nouvel item',
  REVIEW: 'Révision espacée',
  LAB: 'Source tour / lab',
  ASSESS: 'Assessment de lot',
  MOCK: 'Mock exam',
  CONSOLIDATION: 'Consolidation',
  EXAM: 'Examen',
};

/** Minutes since midnight, from `HH:MM`. */
export function toMinutes(hhmm: string): number {
  const [h, m] = hhmm.split(':');
  return Number(h) * 60 + Number(m);
}

export function formatDuration(minutes: number): string {
  if (minutes < 60) {
    return `${minutes} min`;
  }
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m === 0 ? `${h} h` : `${h} h ${String(m).padStart(2, '0')}`;
}

const JOURS = ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'];
const MOIS = [
  'janvier', 'février', 'mars', 'avril', 'mai', 'juin',
  'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre',
];

/**
 * Dates are parsed as UTC and formatted by hand rather than through
 * `toLocaleDateString`. A calendar built from `new Date('2026-10-01')` and
 * read in a negative-offset timezone renders the day before, which would put
 * every session on the wrong square for a whole hemisphere.
 */
export function parseDay(iso: string): Date {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

export function isoOf(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/** Monday-based weekday index, 0 = lundi. */
export function weekdayIndex(date: Date): number {
  return (date.getUTCDay() + 6) % 7;
}

export function dayLabel(date: Date): string {
  return `${JOURS[weekdayIndex(date)]} ${date.getUTCDate()} ${MOIS[date.getUTCMonth()]} ${date.getUTCFullYear()}`;
}

export function monthLabel(date: Date): string {
  return `${MOIS[date.getUTCMonth()]} ${date.getUTCFullYear()}`;
}

export function shortDayName(index: number): string {
  return JOURS[index].slice(0, 3);
}

export function addDays(date: Date, n: number): Date {
  return new Date(date.getTime() + n * 86400000);
}

/** The Monday of the week containing `date`. */
export function startOfWeek(date: Date): Date {
  return addDays(date, -weekdayIndex(date));
}

export function startOfMonth(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1));
}

export function addMonths(date: Date, n: number): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + n, 1));
}

export function sameMonth(a: Date, b: Date): boolean {
  return a.getUTCFullYear() === b.getUTCFullYear() && a.getUTCMonth() === b.getUTCMonth();
}

/**
 * The hour band a week view must cover: the earliest start and latest end of
 * anything actually planned that week, widened to whole hours. Fixing the band
 * at 08:00-22:00 would leave most weeks mostly empty, because weekday sessions
 * begin at 18:00 and weekend ones at 09:00.
 */
export function hourBand(days: PlanDay[]): [number, number] {
  let first = 24 * 60;
  let last = 0;

  for (const day of days) {
    for (const event of day.events) {
      first = Math.min(first, toMinutes(event.start));
      last = Math.max(last, toMinutes(event.end));
    }
  }

  if (last === 0) {
    return [9, 12];
  }

  return [Math.floor(first / 60), Math.ceil(last / 60)];
}
