import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {themes as prismThemes} from 'prism-react-renderer';

/**
 * Documentation-site presentation layer (ADR-0003).
 *
 * Content under `website/docs/` is GENERATED by `php bin/cert build` from the
 * canonical YAML. Do not edit it by hand — the generator overwrites it, and the
 * canonical data is the single source of truth (Master Plan §11).
 */
const config: Config = {
  title: 'Symfony 8 Certification Path',
  tagline: 'Préparation ciblée à la certification Symfony 8.0',
  favicon: 'img/favicon.svg',

  url: 'https://jasseryahyaoui.github.io',
  baseUrl: '/Symfony-8-Certification-Path/',

  organizationName: 'jasserYahyaoui',
  projectName: 'Symfony-8-Certification-Path',
  trailingSlash: false,

  // A broken link means a learner hits a dead end, so it fails the build
  // rather than shipping. This mirrors CI rule LNK-001 for the site itself.
  onBrokenLinks: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'fr',
    locales: ['fr'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          editUrl:
            'https://github.com/jasserYahyaoui/Symfony-8-Certification-Path/tree/master/',
          showLastUpdateTime: false,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Symfony 8 Certification',
      logo: {
        alt: '',
        src: 'img/logo.svg',
      },
      items: [
        {type: 'docSidebar', sidebarId: 'main', position: 'left', label: 'Documentation'},
        {to: '/calendar', label: 'Agenda', position: 'left'},
        {to: '/docs/revision/roadmap', label: 'Plan de révision', position: 'left'},
        {to: '/practice', label: 'Practice Mode', position: 'left'},
        {to: '/exam', label: 'Exam Mode', position: 'left'},
        // The five mocks were published, deployed and smoke-tested, and linked
        // from nowhere: a crawl of the built site on 2026-09-15 found 208 pages,
        // 203 reachable by clicking, and exactly these 5 orphaned. Every gate was
        // green because each visits them by a hardcoded URL list, and
        // `onBrokenLinks` catches broken links, never missing ones. The learner
        // had to type the address. Labels are the blueprint's own names.
        {
          type: 'dropdown',
          label: 'Simulations',
          position: 'left',
          items: [
            {to: '/mock-1', label: 'Mock 1 — Knowledge'},
            {to: '/mock-2', label: 'Mock 2 — Application'},
            {to: '/mock-3', label: 'Mock 3 — Certification difficulty'},
            {to: '/mock-5', label: 'Mock 5 — Weakness-based'},
            // Last, and named for what it costs: Mock 4 is the holdout, meant to
            // be sat once. A label that reads like the others invites a click
            // that cannot be taken back.
            {to: '/mock-4', label: 'Mock 4 — finale, à ne passer qu\'une fois'},
          ],
        },
        {
          href: 'https://github.com/jasserYahyaoui/Symfony-8-Certification-Path',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'light',
      links: [
        {
          title: 'Apprendre',
          items: [
            {label: 'Introduction', to: '/docs'},
            {label: 'Plan de révision', to: '/docs/revision/roadmap'},
            {label: 'Agenda (vue calendrier)', to: '/calendar'},
            {label: 'Calendrier jour par jour', to: '/docs/revision/calendar'},
            {label: 'Couverture officielle', to: '/docs/syllabus/coverage'},
            {label: 'Exclusions', to: '/docs/syllabus/exclusions'},
          ],
        },
        {
          title: "S'évaluer",
          items: [
            {label: 'Practice Mode', to: '/practice'},
            {label: 'Exam Mode', to: '/exam'},
            {label: 'Mock 1 — Knowledge', to: '/mock-1'},
            {label: 'Mock 2 — Application', to: '/mock-2'},
            {label: 'Mock 3 — Certification difficulty', to: '/mock-3'},
            {label: 'Mock 5 — Weakness-based', to: '/mock-5'},
            {label: 'Mock 4 — finale, à ne passer qu\'une fois', to: '/mock-4'},
            {label: 'Ma progression', to: '/progression'},
          ],
        },
        {
          title: 'Projet',
          items: [
            {
              label: 'Dépôt GitHub',
              href: 'https://github.com/jasserYahyaoui/Symfony-8-Certification-Path',
            },
          ],
        },
      ],
      copyright:
        'Progression stockée localement dans votre navigateur. Aucun compte, aucune donnée envoyée.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // `twig` is deliberately absent: Prism's templating languages assume a
      // global `Prism`, which the Docusaurus 3.10 SSR bundle does not provide,
      // and adding it fails the build with "Prism is not defined". Twig samples
      // for Lot 6 should be fenced as `html` until that is resolved upstream.
      additionalLanguages: ['bash', 'yaml', 'php'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
