import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated from the directory structure that `php bin/cert build` writes,
 * so adding an official item to the matrix adds it to the sidebar without a
 * second place to keep in sync.
 */
const sidebars: SidebarsConfig = {
  main: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
